linters:
  enable:
    - goimports
  disable:
    - asciicheck
    - contextcheck
    - forcetypeassert
    - gocritic
    - godot
    - gofmt
    - misspell
    - stylecheck

run:
  deadline: 10m

linters-settings:
  goimports:
    local-prefixes: github.com/spheronFdn/go-nvml
